# <!-- In July 2011, the final NASA Space Shuttle mission launched from the Kennedy Space Center.

# Write a program to run the countdown sequence for the shuttle launch. Your program should work like this:

# Time to launch: 10
# Counting down ...
# 10 ...
# 9 ...
# 8 ...
# 7 ...
# 6 ...
# 5 ...
# 4 ...
# 3 ...
# 2 ...
# 1 ...
# Lift Off!
# ​ -->



j =0
k = int(input("Time to launch: "))
print ("Counting down ...")

while k > j:
  print (k , "...")
  k-=1
print ("Lift Off!")